### ISSUE TITLE
NumLock state always remains on

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope-NumPad#1]
Very, very tiny thing, but when I use another keyboard to turn `NumLock` off, then turn the `NUMPAD` layer of the Model01 on, then off again, `NumLock` remain on, even though one may expect it to turn back off.

**Comment by slburson** [comment]
I see the same thing sometimes,  but not always, and I haven't figured out what causes it.  I pulled up `xev`, and saw that sometimes, when I engage the numpad, I get an apparently infinite stream of KeyRelease/KeyPress pairs with keycode 77 (Num_Lock), 40ms apart (that is, the timestamps of the release and press are equal, and then the next pair is 40ms later).  The stream stops when I hit any other key (I think; it's possible that it has to be a numpad key).  Sometimes, but not always, there's an initial KeyPress event, followed 600ms later by the first KeyRelease/KeyPress pair; I guess that happens only the first time.

Notice that when I hit another key, the state it stops in is one in which the last event of the stream was a KeyPress.  This is why I suspect we're seeing the same phenomenon.  Also I don't think I've seen a case where NumLock was stuck on and I didn't get the infinite stream of release/press pairs when I checked with `xev`.

I'm mostly seeing this with my customized keymap, but I did get it to happen once with the default keymap, though I couldn't figure out how to make it happen again, even after power-cycling the keyboard.  (My customized keymap uses Fn-Num to engage the numpad.)

**Comment by obra** [comment]
I don't think those two things are quite the same issue, but it's the same little bit of code causing both problems. For @slburson's issue, I think the issue is:

"e’re calling “pressKey” but not ever releaseKey. That’s totally a bug. so I think this may be a weird key repeat issue."

**Comment by MartyGentillon** [comment]
in short, the cause is that, when the number pad is activated, and numlock is not on, it activates it.  It does not, however restore the former state before it deactivates.  The two patches above add this functionality.
