### ISSUE TITLE
Numpad not working

### ISSUE THREAD

**Issue by kriber82** [keyboardio/Kaleidoscope-NumPad#14]
Observed: When pressing num key on model 01, numpad layer is not activated and LEDs do not signal activated numpad either.

Expected: When pressing num key on model 01, numpad layer activation on model 01 should toggle.  LEDs should signal numpad activation.

Additional info: Running on Windows 10. Firmware built from Kaleidoscope.ino (commit cdc2115). Numpad on other attached keyboard is correctly toggled when pressing num key on model 01.

**Comment by algernon** [comment]
It's probably `kaleidoscope::hid::getKeyboardLEDs()` (and the supporting code) not working properly, and failing to sync numlock state. At least, that's what seems to be the case based on your testing (thanks a lot for that, it makes it so much easier to narrow down the bug!).

Will look into it, thanks!

**Comment by antonkai2k** [comment]
I confirm `kaleidoscope::hid::getKeyboardLEDs()` doesn't really work, on macOS in my case.
I try to detect `CapsLock` without success as described [here](https://github.com/keyboardio/Kaleidoscope/issues/219#issuecomment-356251861).
Latest firmware at this moment.

As I understand, this should get the status directly from the OS, right?

**Comment by obra** [comment]
It should, so long as the OS is reporting them to us.
ᐧ

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#381.
