### ISSUE TITLE
Stuck in an infinite loop

### ISSUE THREAD

**Issue by exlee** [keyboardio/Kaleidoscope-NumPad#18]
Hi,

after flashing to the newest firmware version (from the stock firmware) I've noticed, that the num key no longer works.

After further investigation I found out, that after I activate Numpad layer, keyboard is constantly sending NumLock keycodes very rapidly.

![Result of turning numpad on and off for fraction of second](https://user-images.githubusercontent.com/3380474/44460057-05af6800-a60c-11e8-9d28-d1e0a84d2441.png)
----
Edit:
I've removed NumPad from the plugins list and NumLock key is no longer stuck. No led lightning, though. Tried to revert last couple commits but to no avail. IMHO this is integration issue.

**Comment by obra** [comment]
Thanks so much for the heads up! Are you using the Arduino-Boards git
master or the v1.90 version from the Arduino IDE?
ᐧ

**Comment by exlee** [comment]
Unfortunately I cannot confirm it now (will be able to do in few hours) but I followed the instruction from QuickStart guide just yesterday, so most it’s highly possible that I do so :)

**Comment by exlee** [comment]
I confirmed that I'm using Arduino-Boards master, as described [here](https://github.com/keyboardio/Model01-Firmware). Also I'm building from CLI.

**Comment by obra** [comment]
Hi! I've reproduced this locally. I'm trying to dig into this. I'm hoping I
can get somewhere with it tonight.
ᐧ
