### ISSUE TITLE
Replace built-in layer highlight effect with bjc/Kaleidoscope-LayerHighlighter

### ISSUE THREAD

**Issue by bjc** [keyboardio/Kaleidoscope-NumPad#21]
I've extracted the highlight functionality from NumPad into a separate, more general, plugin at https://github.com/bjc/Kaleidoscope-LayerHighlighter which can be used for multiple projects.

PS, Gergely asked me to open this issue as a gentle reminder 😉

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#380.
