### ISSUE TITLE
Numpad causing major slowdown

### ISSUE THREAD

**Issue by jhitch** [keyboardio/Kaleidoscope-NumPad#22]
As of yesterday, I have updated my libraries and firmware. I noticed a dramatic hit to my Mac's performance when I engage Numlock. No matter what program is active (Safari, Chrome, Word), the instant that I activate my Numpad layer, the CPU usage spikes. On Activity Monitor, the culprit is WindowServer, which immediately begins to occupy 100% of my CPU. As soon as I turn off my Numpad, the CPU usage returns to normal. The problem is repeatable.

At times, the computer makes sounds as if many unexpected keypresses are being received, but I can't replicate this every time.

**Comment by obra** [comment]
Hi, 

Can you tell me what version of Kaleidoscope-Numpad you’re running? Are you running from a git checkout of Arduino-Boards, Kaleidoscope-Bundle-Keyboardio, or from the Arduino Boards Manager?

**Comment by jhitch** [comment]
I pulled the most recent version of the firmware and updated my libraries and submodules using Terminal. Then I modified the firmware before using Arduino IDE to upload it. I'm not sure that I am answering your question.

**Comment by algernon** [comment]
This *sounds* like as if NumLock would be toggling on and off repeatedly. That might overwhelm the host if it tries to react to that in any non-trivial way. But this is just a suspicion.

Which version of OSX are you running?

**Comment by obra** [comment]
right. i thought this was an issue we’d already fixed.

**Comment by jhitch** [comment]
This was on High Sierra. I just tested it on Mojave. Still doing the same thing.

**Comment by obra** [comment]
Right. I want to make sure you’re actually on the current rev. That’ll help me track the issue down.  Can you tell me what the first couple lines of “git log” inside of libraries/Kaleidoscope-NumPad look like?

**Comment by jhitch** [comment]
Forgive me, I don't see anything resembling "git log" inside that folder even when I look for hidden files. This is the contents of the library.properties file:

name=Kaleidoscope-NumPad
version=0.0.1
author=Jesse Vincent
maintainer=Jesse Vincent <jesse@keyboard.io>
sentence=A NumPad plugin for Kaleidoscope.
paragraph=...
category=Communication
url=https://github.com/keyboardio/Kaleidoscope-NumPad
architectures=avr
dot_a_linkage=true


And this is the contents of .travis.yml which looks to contain relevant information:

dist: trusty
sudo: false
os:
  - linux
install:
  - git clone --depth 1 --recurse-submodules https://github.com/keyboardio/Arduino-Boards hardware/keyboardio/avr
script:
  - make travis-test BOARD_HARDWARE_PATH=$(pwd)/hardware
notifications:
  irc:
    channels:
      - "chat.freenode.net#keyboardio"
    use_notice: true
    skip_join: true
    template:
      - "%{repository_name}/%{branch} %{commit} by %{author}: %{commit_subject} %{build_url} %{message}" 
  email:
    on_success: change
    on_failure: change
cache:
  ccache: true

Give me more instructions if I can be of more help.

**Comment by obra** [comment]
Hi,

Sorry for the delay in my reply.

cd
~/Documents/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope-NumPad/
git log

Specifically, I'm looking to see if that history includes:

commit d931ae1efa0c4a4b6a0baa4daf5f83efd3ac3f94
Merge: f9e1578 e3acde9
Author: Jesse Vincent <jesse@fsck.com>
Date:   Fri Aug 24 23:32:48 2018 -0700

    Merge pull request #20 from keyboardio/bug/numlock-sync-report-spam

    Bug/numlock sync report spam

However! From your .travis.yml, I think I know what's up.

Can you try removing arduino/hardware/keyboardio and then doing a fresh
clone of:

https://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio into

~/Documents/Arduino/hardware/keyboardio

If you get the path correct, that keyboardio directory should contain these
files:

avr  build-tools  COPYING  Makefile  README.md  toolchain  x86

I think that'll get you up to the correct current version that will fix the
issue you're seeing.

ᐧ

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#379.

**Comment by jhitch** [comment]
Yep. Jesse's comment was spot on. I don't know what had gone wrong, but when I deleted the contents of my hardware directory and rebuilt it from scratch the problem was resolved.
