### ISSUE TITLE
Pressing led key 4 times and num key one reboots the firmware

### ISSUE THREAD

**Issue by LA-Toth** [keyboardio/Kaleidoscope-NumPad#9]
If Numpad is in KALEIDOSCOPE_INIT_PLUGINS and I press the following 5 keys in any order, the firmware restarts itself.
The keys: "led" key four times and "num" key once.

I reproduced it one the default Model01-Firmware, but I noticed it on my custom firmware.

**Comment by obra** [comment]
@algernon - any idea?

**Comment by LA-Toth** [comment]
I played around a little bit, and perhaps it's related to power consumption, ie. if I use only active mod color, numpad, and solid color as led effects, and the solid color is (255, 255, 255), it has strange behavior: sometimes the white is fine, but mostly it is blinky, and with numpad it is more unstable. I use a 7 years old Mac, but it does not seem to be relevant.

**Comment by obra** [comment]
It is indeed 100% possible to pull more power than the USB current limiter can pull. But all of the default LED modes should be calibrated not to do that.

**Comment by LA-Toth** [comment]
Okay I'm 99% certain it's the power, as I only have issues when the USB cannot provide more power than 500mA. Plugging in the Model01 into my Apple Keyboard the power is limited to 500mA, and the Mac itself can provide more power - in the latter case the problem does not occur. This page states the power limit: https://support.apple.com/en-us/HT204377

**Comment by algernon** [comment]
If it is power related... does it help if you change [numpad_color](https://github.com/keyboardio/Kaleidoscope-NumPad/blob/2bdc07b7bd748046aee4294cafda71d7bd95603a/src/Kaleidoscope-NumPad.cpp#L10) to `CRGB(160, 0, 0)` instead?

**Comment by LA-Toth** [comment]
Yes, 160, 0, 0 is fine. Anyway, 200, 0, 0 also work for me in case of the default firmware.
The problematic led effect was the solidRed, with RGB 160, 0, 0.

**Comment by algernon** [comment]
I think the problem was going form R160 to R255, that might have resulted in a spike the host didn't like. If R160 is fine, lets default NumPad to that too, thus working around the issue until we have proper power negotiation and tracking.
